
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3307
      - MYSQL_USER=nhattin
      - MYSQL_PASSWORD=nhattin
      - MYSQL_ROOT_PASSWORD=nhattin
      - MYSQL_DATABASE=scientist_community
      - MONGO_URI=mongodb+srv://tachithanhdanh:Phl4nljXagrwWiy7@danhcluster.uyk5rdp.mongodb.net/ds-talent?retryWrites=true&w=majority
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=nhattin
      - MYSQL_DATABASE=scientist_community
      - MYSQL_USER=nhattin
      - MYSQL_PASSWORD=nhattin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: